/*
Copyright 2026 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package cachekey derives a SourceDefinition's cache key from the context its
// template reads.
//
// The key is generated at build time by `vela def` and validated at admission, so
// nothing infers at reconcile time: the controller evaluates the generated
// expression exactly as it would an authored one.
//
// Policy - which fields count, in what order - lives in an embedded CUE file whose
// hash is the version identity. Mechanism lives here.
package cachekey

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"sync"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
)

//go:embed rules/*.cue
var rulesFS embed.FS

// keyedField is a context field that contributes to the key.
type keyedField struct {
	Order int `json:"order"`
	// Indexed means the read carries a literal index - context.appLabels["team"] -
	// so each index read contributes separately.
	Indexed bool `json:"indexed"`
	// Segment means the value is also inlined into the readable prefix. It says
	// nothing about correctness: every field contributes to the hash regardless.
	Segment bool `json:"segment"`
}

// Rules is one version of the inference policy, identified by the hash of the
// file it was loaded from.
type Rules struct {
	// Hash identifies this policy. It is stamped onto generated definitions and
	// used to load the same rules again when validating them.
	Hash string
	// Version is a readable name for the same policy, declared in the rules file
	// so it cannot drift from the content it names. Stamped alongside the hash
	// for whoever is reading an annotation rather than computing one.
	Version string

	keyed map[string]keyedField
}

// LoadRules returns the current rules - the latest file in the embedded set.
func LoadRules() (*Rules, error) {
	names, err := ruleFileNames()
	if err != nil {
		return nil, err
	}
	return loadRuleFile(names[len(names)-1])
}

// LoadRulesByHash returns the rules with the given hash, for validating a
// definition generated against an earlier policy. A missing hash is an error
// rather than a fallback: silently validating against different rules than the
// ones used to generate would defeat the point of recording it.
func LoadRulesByHash(hash string) (*Rules, error) {
	names, err := ruleFileNames()
	if err != nil {
		return nil, err
	}
	for _, name := range names {
		r, err := loadRuleFile(name)
		if err != nil {
			return nil, err
		}
		if r.Hash == hash {
			return r, nil
		}
	}
	return nil, fmt.Errorf("no cache-key rules with hash %q are embedded in this build; "+
		"the definition was generated by a version whose rules are not present", hash)
}

func ruleFileNames() ([]string, error) {
	entries, err := rulesFS.ReadDir("rules")
	if err != nil {
		return nil, fmt.Errorf("reading embedded rules: %w", err)
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() {
			names = append(names, "rules/"+e.Name())
		}
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("no cache-key rules are embedded in this build")
	}
	sort.Strings(names)
	return names, nil
}

// loadedRules memoises the parsed rule files.
//
// The rules live in an embedded FS, so a file's content cannot change while the
// process runs and parsing it twice can only produce the same answer. It was
// being parsed on every source resolution - a fresh cue.Context, a compile of
// the rules file and a policy hash, all to answer a question with one possible
// answer - which made it most of what a render spent on an already-cached
// source.
//
// The returned *Rules is shared. Nothing mutates one: Hash and Version are
// written only here, and keyed is unexported and read through Fields.
var loadedRules sync.Map // name -> *Rules

func loadRuleFile(name string) (*Rules, error) {
	if hit, ok := loadedRules.Load(name); ok {
		return hit.(*Rules), nil
	}
	rules, err := parseRuleFile(name)
	if err != nil {
		return nil, err
	}
	loadedRules.Store(name, rules)
	return rules, nil
}

func parseRuleFile(name string) (*Rules, error) {
	raw, err := rulesFS.ReadFile(name)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", name, err)
	}

	rules := &Rules{keyed: map[string]keyedField{}}

	v := cuecontext.New().CompileBytes(raw)
	if v.Err() != nil {
		return nil, fmt.Errorf("compiling %s: %w", name, v.Err())
	}
	if err := v.LookupPath(cue.ParsePath("keyed")).Decode(&rules.keyed); err != nil {
		return nil, fmt.Errorf("decoding keyed fields from %s: %w", name, err)
	}
	if err := v.LookupPath(cue.ParsePath("version")).Decode(&rules.Version); err != nil {
		return nil, fmt.Errorf("decoding version from %s: %w", name, err)
	}
	if rules.Version == "" {
		return nil, fmt.Errorf("%s declares no version; it names the policy for anyone reading a stamped definition", name)
	}

	hash, err := rules.policyHash()
	if err != nil {
		return nil, fmt.Errorf("hashing %s: %w", name, err)
	}
	rules.Hash = hash
	return rules, nil
}

// policyHash fingerprints what these rules *do*, not the file they came from.
//
// Comments and the declared version are not part of the policy, and hashing the
// raw bytes would make editing either change the identity - invalidating every
// definition already stamped, for no behavioural reason. Only the keyed list is
// covered: which context is readable, in what order, and whether it is indexed.
func (r *Rules) policyHash() (string, error) {
	// json.Marshal sorts map keys, so this does not depend on iteration order.
	raw, err := json.Marshal(r.keyed)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(raw)
	return hex.EncodeToString(sum[:])[:8], nil
}

// keyedEntry returns the ordering entry for a context field, and whether the
// field may be read at all. Anything absent is unsupported.
func (r *Rules) keyedEntry(field string) (keyedField, bool) {
	e, ok := r.keyed[field]
	return e, ok
}

// Fields returns every readable context field, in key order. The resolver builds
// a source's context from this, so a field that is not keyed is not merely
// rejected - it is absent, and cannot be read even where admission is disabled.
func (r *Rules) Fields() []string {
	fields := make([]string, 0, len(r.keyed))
	for field := range r.keyed {
		fields = append(fields, field)
	}
	sort.Slice(fields, func(i, j int) bool {
		return r.keyed[fields[i]].Order < r.keyed[fields[j]].Order
	})
	return fields
}
