/*
Copyright 2026 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package sourcedefinition

import (
	"context"
	"fmt"
	"net/http"
	"time"

	admissionv1 "k8s.io/api/admission/v1"
	apiequality "k8s.io/apimachinery/pkg/api/equality"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/manager"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"

	"github.com/oam-dev/kubevela/apis/core.oam.dev/v1beta1"
	"github.com/oam-dev/kubevela/pkg/definition/cachekey"
	"github.com/oam-dev/kubevela/pkg/logging"
	"github.com/oam-dev/kubevela/pkg/oam"
	webhookutils "github.com/oam-dev/kubevela/pkg/webhook/utils"
)

var sourceDefGVR = v1beta1.SourceDefinitionGVR

// ValidatingHandler handles validation of SourceDefinition.
type ValidatingHandler struct {
	Client client.Client
	// Decoder decodes objects
	Decoder admission.Decoder
}

var _ admission.Handler = &ValidatingHandler{}

// Handle validates a SourceDefinition on create and update.
func (h *ValidatingHandler) Handle(ctx context.Context, req admission.Request) admission.Response {
	startTime := time.Now()
	ctx = logging.WithRequestID(ctx, string(req.UID))
	logger := logging.NewHandlerLogger(ctx, req, "SourceDefinitionValidator")

	logger.WithStep("start").Info("Starting admission validation for SourceDefinition resource", "operation", req.Operation, "resourceVersion", req.Kind.Version)

	if req.Resource.String() != sourceDefGVR.String() {
		err := fmt.Errorf("expect resource to be %s", sourceDefGVR)
		logger.WithStep("resource-check").WithError(err).Error(err, "Admission request targets unexpected resource type - rejecting request",
			"expected", sourceDefGVR.String(),
			"actual", req.Resource.String(),
			"operation", req.Operation)
		return admission.Errored(http.StatusBadRequest, fmt.Errorf("%s (requestUID=%s)", err.Error(), req.UID))
	}

	if req.Operation != admissionv1.Create && req.Operation != admissionv1.Update {
		logger.WithStep("skip-validation").Info("Skipping SourceDefinition validation - operation does not require validation", "operation", req.Operation, "reason", "only CREATE and UPDATE operations are validated")
		return admission.ValidationResponse(true, "")
	}

	obj := &v1beta1.SourceDefinition{}
	if err := h.Decoder.Decode(req, obj); err != nil {
		logger.WithStep("decode").WithError(err).Error(err, "Unable to decode admission request payload into SourceDefinition object - malformed request")
		return admission.Errored(http.StatusBadRequest, fmt.Errorf("%s (requestUID=%s)", err.Error(), req.UID))
	}

	// A metadata-only update makes no new claim about the spec, and the spec was
	// validated when it was written. Skipping is not just an optimisation: a
	// definition generated by an older release records cache-key rules this build
	// does not embed, so re-running the gates turns `kubectl label` on it into a
	// denial about cache keys, and the object cannot be labelled, annotated or
	// adopted by Helm until somebody rewrites its spec.
	//
	// An old object that will not decode falls through to full validation rather
	// than being waved past.
	if req.Operation == admissionv1.Update && len(req.OldObject.Raw) > 0 {
		old := &v1beta1.SourceDefinition{}
		if err := h.Decoder.DecodeRaw(req.OldObject, old); err == nil &&
			apiequality.Semantic.DeepEqual(old.Spec, obj.Spec) {
			logger.WithStep("skip-validation").Info("Skipping SourceDefinition validation - spec is unchanged", "reason", "metadata-only update")
			return admission.ValidationResponse(true, "")
		}
	}

	if obj.Spec.Schematic == nil || obj.Spec.Schematic.CUE == nil {
		err := fmt.Errorf("SourceDefinition must declare spec.schematic.cue")
		logger.WithStep("validate-schematic").WithError(err).Error(err, "SourceDefinition has no CUE schematic - resolution logic is required")
		return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
	}
	cueTemplate := obj.Spec.Schematic.CUE.Template

	logger.WithStep("validate-cue").Info("Validating CUE template syntax and semantics for SourceDefinition schematic")
	// Without executing the providers: a source exists to fetch something, and
	// admission has no parameters to hand them. Compiled against SourceCompiler,
	// so a template importing a package a source may not use is refused here
	// rather than at its first resolve.
	if err := webhookutils.ValidateSourceTemplate(ctx, cueTemplate); err != nil {
		logger.WithStep("validate-cue").WithError(err).Error(err, "CUE template contains syntax errors or invalid constructs - template compilation failed")
		return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
	}

	// A SourceDefinition without a storage key has no deterministic cache
	// identity; reject it here rather than synthesising one at resolution time.
	if err := ValidateSourceStorage(cueTemplate); err != nil {
		logger.WithStep("validate-storage").WithError(err).Error(err, "SourceDefinition storage block is invalid - a cache key is required")
		return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
	}

	// Without a schema: block, both the admission path check and the runtime
	// output check are skipped, leaving source reads unvalidated in either layer.
	if err := ValidateSourceSchema(cueTemplate); err != nil {
		logger.WithStep("validate-schema").WithError(err).Error(err, "SourceDefinition schema block is invalid - a schema is required to validate source reads")
		return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
	}

	// storage.key is computed from the context the template reads. The CLI writes
	// it, but nothing stops an object being edited or written by hand, so re-derive
	// it here rather than trusting what arrived. The rules recorded on the object
	// are used in preference to the current ones, so changing inference does not
	// invalidate definitions already committed and re-applied by GitOps.
	if err := cachekey.Verify(obj.Name, cueTemplate, obj.GetAnnotations()[cachekey.RulesAnnotation]); err != nil {
		logger.WithStep("validate-cache-key").WithError(err).Error(err, "SourceDefinition cache key does not match the context its template reads")
		return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
	}

	// consumableFrom is optional, but a malformed one must not be accepted and
	// then silently ignored when an Application binds the source.
	consumable, err := ParseConsumableFrom(cueTemplate)
	if err != nil {
		logger.WithStep("validate-consumable-from").WithError(err).Error(err, "SourceDefinition consumableFrom is invalid")
		return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
	}

	// A definition that can never resolve where it says it may be consumed is
	// wrong on its own terms, and says so now rather than when someone binds it.
	if err := ValidateSurfaceCompatibility(cueTemplate, consumable); err != nil {
		logger.WithStep("validate-surface-compatibility").WithError(err).Error(err, "SourceDefinition cannot resolve on the surfaces it declares")
		return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
	}

	// spec.version is what makes each version a distinct DefinitionRevision, so
	// a malformed one is accepted here and fails when reconciliation tries to
	// parse it, leaving the definition unusable. The other definition kinds
	// validate it at admission; sources do the same.
	if obj.Spec.Version != "" {
		if err := webhookutils.ValidateSemanticVersion(obj.Spec.Version); err != nil {
			logger.WithStep("validate-version").WithError(err).Error(err, "SourceDefinition version does not follow semantic versioning format (x.y.z)", "version", obj.Spec.Version)
			return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
		}
	}

	revisionName := obj.GetAnnotations()[oam.AnnotationDefinitionRevisionName]
	if revisionName != "" {
		defRevName := fmt.Sprintf("%s-v%s", obj.Name, revisionName)
		if err := webhookutils.ValidateDefinitionRevision(ctx, h.Client, obj,
			client.ObjectKey{Namespace: obj.Namespace, Name: defRevName}); err != nil {
			logger.WithStep("validate-revision").WithError(err).Error(err, "SourceDefinition revision conflicts with an existing revision or has an invalid format", "revisionName", revisionName)
			return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
		}
	}

	// Both name the revision, and they can disagree.
	if err := webhookutils.ValidateMultipleDefVersionsNotPresent(obj.Spec.Version, revisionName, obj.Kind); err != nil {
		logger.WithStep("validate-version-conflict").WithError(err).Error(err, "SourceDefinition sets both spec.version and the revision annotation", "specVersion", obj.Spec.Version, "revisionName", revisionName)
		return admission.Denied(fmt.Sprintf("%s (requestUID=%s)", err.Error(), req.UID))
	}

	logger.WithStep("complete").WithSuccess(true, startTime).Info("SourceDefinition admission validation completed successfully - resource is valid and will be admitted", "definitionName", obj.Name, "operation", req.Operation)
	return admission.ValidationResponse(true, "")
}

// RegisterValidatingHandler registers SourceDefinition validation with the webhook server.
func RegisterValidatingHandler(mgr manager.Manager) {
	server := mgr.GetWebhookServer()
	server.Register("/validating-core-oam-dev-v1beta1-sourcedefinitions", &webhook.Admission{Handler: &ValidatingHandler{
		Client:  mgr.GetClient(),
		Decoder: admission.NewDecoder(mgr.GetScheme()),
	}})
}
