// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: pkg/proto/model/install.proto

package model

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallVela struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster  string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Helmrepo string `protobuf:"bytes,2,opt,name=helmrepo,proto3" json:"helmrepo,omitempty"`
	Version  string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *InstallVela) Reset() {
	*x = InstallVela{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_model_install_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallVela) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallVela) ProtoMessage() {}

func (x *InstallVela) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_install_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallVela.ProtoReflect.Descriptor instead.
func (*InstallVela) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_install_proto_rawDescGZIP(), []int{0}
}

func (x *InstallVela) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *InstallVela) GetHelmrepo() string {
	if x != nil {
		return x.Helmrepo
	}
	return ""
}

func (x *InstallVela) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InstallVelaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *InstallVelaResponse) Reset() {
	*x = InstallVelaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_model_install_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallVelaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallVelaResponse) ProtoMessage() {}

func (x *InstallVelaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_model_install_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallVelaResponse.ProtoReflect.Descriptor instead.
func (*InstallVelaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_model_install_proto_rawDescGZIP(), []int{1}
}

func (x *InstallVelaResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_pkg_proto_model_install_proto protoreflect.FileDescriptor

var file_pkg_proto_model_install_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22,
	0x5d, 0x0a, 0x0b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x56, 0x65, 0x6c, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x6c, 0x6d,
	0x72, 0x65, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x6c, 0x6d,
	0x72, 0x65, 0x70, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2f,
	0x0a, 0x13, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x56, 0x65, 0x6c, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42,
	0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x61,
	0x6d, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x76, 0x65, 0x6c, 0x61, 0x63, 0x70, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_model_install_proto_rawDescOnce sync.Once
	file_pkg_proto_model_install_proto_rawDescData = file_pkg_proto_model_install_proto_rawDesc
)

func file_pkg_proto_model_install_proto_rawDescGZIP() []byte {
	file_pkg_proto_model_install_proto_rawDescOnce.Do(func() {
		file_pkg_proto_model_install_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_model_install_proto_rawDescData)
	})
	return file_pkg_proto_model_install_proto_rawDescData
}

var file_pkg_proto_model_install_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_model_install_proto_goTypes = []interface{}{
	(*InstallVela)(nil),         // 0: vela.api.model.InstallVela
	(*InstallVelaResponse)(nil), // 1: vela.api.model.InstallVelaResponse
}
var file_pkg_proto_model_install_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_model_install_proto_init() }
func file_pkg_proto_model_install_proto_init() {
	if File_pkg_proto_model_install_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_model_install_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallVela); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_model_install_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallVelaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_model_install_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_model_install_proto_goTypes,
		DependencyIndexes: file_pkg_proto_model_install_proto_depIdxs,
		MessageInfos:      file_pkg_proto_model_install_proto_msgTypes,
	}.Build()
	File_pkg_proto_model_install_proto = out.File
	file_pkg_proto_model_install_proto_rawDesc = nil
	file_pkg_proto_model_install_proto_goTypes = nil
	file_pkg_proto_model_install_proto_depIdxs = nil
}
